package wen.xiao.com.simpleproject.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import wen.xiao.com.simpleproject.entity.ces;

import wen.xiao.com.simpleproject.greendao.cesDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig cesDaoConfig;

    private final cesDao cesDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        cesDaoConfig = daoConfigMap.get(cesDao.class).clone();
        cesDaoConfig.initIdentityScope(type);

        cesDao = new cesDao(cesDaoConfig, this);

        registerDao(ces.class, cesDao);
    }
    
    public void clear() {
        cesDaoConfig.clearIdentityScope();
    }

    public cesDao getCesDao() {
        return cesDao;
    }

}
